# Generated by Django 4.2.1 on 2023-07-14 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploaded_files/', verbose_name='上传的文件')),
                ('train_result_file', models.FileField(upload_to='train_result_file/', verbose_name='训练结果文件')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('train_status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成')], default='pending', max_length=50, verbose_name='诊断任务状态')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='归属的用户')),
            ],
            options={
                'verbose_name': '训练任务',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='反馈标题')),
                ('content', models.TextField(max_length=25565, verbose_name='反馈内容')),
                ('reply', models.TextField(max_length=25565, verbose_name='答复内容')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('feedback_status', models.CharField(choices=[('processing', '处理中'), ('completed', '已完成')], default='processing', max_length=50, verbose_name='任务状态')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='归属的用户')),
            ],
            options={
                'verbose_name': '训练任务',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DiagnosisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploaded_files/', verbose_name='上传的文件')),
                ('diagnosis_result_file', models.FileField(upload_to='diagnosis_result_file/', verbose_name='诊断结果文件')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('diagnosis_status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成')], default='pending', max_length=50, verbose_name='诊断任务状态')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='归属的用户')),
            ],
            options={
                'verbose_name': '诊断任务',
                'ordering': ('-created',),
            },
        ),
    ]
